<?php

/**
 * @file
 * Contains custom_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param RouteMatchInterface $route_match
 *
 * @return string
 */

function custom_events_help($route_name, RouteMatchInterface $route_match) {
 switch ($route_name) {
    case 'help.page.custom_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to provide custom events functionality.') . '</p>';
      return $output;
    default:
  }
}


